### ISSUE TITLE
[Core] - Impending Victory (LvL 30 Warrior Talent) doesn't reset Cooldown after killing an exp granting enemy

### ISSUE THREAD

**Issue by Crzyfist** [GuabinaCore/WoWKoi#518] opened 2020-04-08 19:09 UTC
**Links:** https://wow.gamepedia.com/Impending_Victory

from WoWHead or our Armory

**What is happening:** the cooldown of the spell isn't reseting when killing an enemy that gives exp or honor / it also does not consume the Victory Rush proc, when killing an enemy

**What should happen:** the cooldown should reset

**Comment by Arkanheal** [comment] 2020-04-09 07:16
Duplicate of #14

**Comment by ShikoSCS** [comment] 2020-05-13 21:56
Fixed

**Closed as completed by ShikoSCS** 2020-05-13 21:56 UTC
Labels: Core, Warrior
