### ISSUE TITLE
[Core] - Dk-unholy-runic corruption 

### ISSUE THREAD

**Issue by Theadon45** [GuabinaCore/WoWKoi#1362] opened 2020-05-14 09:21 UTC
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=51462/runic-corruption
**What is happening:**
Spending runic power doesn't activate runic corruption 

**What should happen:**
Spending runic power should proc the passive skill runic corruption

**Comment by Serithul** [comment] 2020-05-16 08:43
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/963

**Closed as completed** 2020-10-19 16:53 UTC
Labels: Core, Death Knight
