### ISSUE TITLE
[Core] - Riding skill achievement bug

### ISSUE THREAD

**Issue by GhostySimon** [GuabinaCore/WoWKoi#891] opened 2020-04-20 00:04 UTC
**Links:**

from WoWHead or our Armory

**What is happening:**

When Paladin learns Apprentice riding skill automatically at level 20 he/she receives all the achievements related to learning riding skill, including artisan riding skill achievement "The right stuff", but skill itself is only in apprentice level.

**What should happen:**

Achievements should be given after you acquire related level of riding skill.

**Comment by Serithul** [comment] 2020-04-20 07:44
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/262

**Comment by Thordekk** [comment] 2020-06-29 11:50
We correct achievement data, try again when fix its applied

**Closed as completed by Thordekk** 2020-06-29 11:50 UTC
Labels: Core, Achievement
