### ISSUE TITLE
[Tyce] - Spell Monk: Fists of furry

### ISSUE THREAD

**Issue by MicuRazvan-Florentin2E3** [GuabinaCore/WoWKoi#2313] opened 2021-04-21 20:22 UTC
Links:

https://www.wowhead.com/spell=113656/fists-of-fury

What is happening:
When your target dies before the channeling is over, it breaks the spell.

What should happen:
This spell should be finished at the end of the duration or when cancelled by using another spell.

**Comment by lemmiwinkss** [comment] 2021-09-05 20:51
As of 05/09/2021 this is still an issue. It has not been fixed.

**Comment by Tarkinug** [comment] 2021-11-19 07:41
Some update the spell finishes we just can't see it. The dam goes on but the visual doesn't also the channeling bar breaks

**Comment by Arkanheal** [comment] 2021-11-24 12:50
Duplicate of #3269

**Closed as completed by Arkanheal** 2021-11-24 12:50 UTC
