### ISSUE TITLE
[Arthas] - Deathknight Starting Area

### ISSUE THREAD

**Issue by bonfim97** [GuabinaCore/WoWKoi#729] opened 2020-04-16 13:54 UTC
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/quest=12687/into-the-realm-of-shadows

**What is happening:**
When reaching the quest AREA Death's Breach appears error "You're in the Wrong Zone".

**What should happen:**
After Reaching the designated Area and clicking the action, the quest should be completed.

**Comment by Serithul** [comment] 2020-04-16 15:25
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/663

**Closed as completed** 2020-10-19 16:55 UTC
