### ISSUE TITLE
Death Knight (Blood) - Ossuary

### ISSUE THREAD

**Issue by Winkoo6** [GuabinaCore/WoWKoi#1542] opened 2020-06-23 11:01 UTC
**Links:**
https://www.wowhead.com/spell=219786/ossuary

**What is happening:**
Seems it's any damage toggle the buff, instead of the Bone Shield stack value change.
If you has 9 Bone Shield and you get a hit, a Bone Shield decreased to 8 and the Ossuary buff disappear, if you do nothing, just waiting, and getting another hit, Bone Shield decreased to 7 and the Ossuary buff appear again. Also now only the damage trigger this buff, so if you has an active Ossuary buff at the end of the fight, and your Bone Shield buff expire, the Ossuary still remain on you.

**What should happen:**
Only the Bone Shield stack value update can trigger this spell, if the shield has at least 5 charges, this buff appear, and permanent, if the shield has less than 5 charges, or expired the buff need to disappear.

**Comment by Velthur-bot-3000** [comment] 2020-06-23 11:04
dupe of #456 opened on Apr 3 by L1n0x, Make sure when posting bug trackers your double checking that it isn't already posted.  If it is, and you think info is missing from that post, then please feel free to comment on that one, instead of opening another ticket.  Thanks for posting as many as you do.

**Comment by Thordekk** [comment] 2020-06-24 00:26
Fixed

**Comment by GuabinaCore** [comment] 2020-06-24 07:55
Fixed, please check

**Closed as completed by GuabinaCore** 2020-06-24 07:55 UTC
