### ISSUE TITLE
[Warrior Spell] Cant use Charge underwater

### ISSUE THREAD

**Issue by Thovia** [GuabinaCore/WoWKoi#1224] opened 2020-05-03 21:02 UTC
**Links:**
https://www.wowhead.com/spell=22911/charge

**What is happening:**

I cant use Charge underwater. I encountered this issue near Camp everstill. Im using Double Time Talent. There was no obstructions in the way that would otherwise prevent me from using Charge.

**What should happen:**
I should be able to charge to enemies underwater just fine.

**Comment by Serithul** [comment] 2020-05-03 21:17
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/101 . It is a vmap issue that is known and is worked on along with a lot of other issues.

**Closed as completed** 2020-05-04 10:10 UTC
