### ISSUE TITLE
[Arthas] - The Stockades crashes client

### ISSUE THREAD

**Issue by Randysandy929** [GuabinaCore/WoWKoi#757] opened 2020-04-16 20:22 UTC
**Links:**

from WoWHead or our Armory

**What is happening:**
Walking past the second sent of rooms in Stockades crashes the client.

**What should happen:**
No crash of client.

**Comment by Serithul** [comment] 2020-04-16 20:24
Duplicate of https://github.com/GuabinaCore/WoWKoi/issues/620 which is a duplicate of https://github.com/GuabinaCore/WoWKoi/issues/442

**Comment by Cefiro-Caecias** [comment] 2020-05-02 01:46
Fixed. Available in the next update.

**Closed as completed by Cefiro-Caecias** 2020-05-02 01:46 UTC
