### ISSUE TITLE
[Core] - Paladin - Judgement

### ISSUE THREAD

**Issue by Serithul** [GuabinaCore/WoWKoi#576] opened 2020-04-11 17:42 UTC
**Links:**
https://www.wowhead.com/spell=275779/judgment
from WoWHead or our Armory

**What is happening:**
Protection: Hits 2 targets at any time.

**What should happen:**
Protection: Should hit only 1 target at all times.

**Comment by Arkanheal** [comment] 2020-04-11 22:40
Duplicate of #32

**Comment by Serithul** [comment] 2020-04-12 07:37
Indeed, but i have reported a protection bug as well. Editing now to remove the Retribution part.

**Comment by ShikoSCS** [comment] 2020-04-18 17:39
Fixed

**Closed as completed by ShikoSCS** 2020-04-18 17:39 UTC
Labels: Core, Paladin
