### ISSUE TITLE
The Skies of Highmountain bug

### ISSUE THREAD

**Issue by Tonage** [GuabinaCore/WoWKoi#3293] opened 2021-11-23 20:23 UTC
**Links:**
https://www.wowhead.com/quest=39387/the-skies-of-highmountain

**What is happening:**
No Lasan comes back to finish his ritual at the base of Thunder Totem.

**What should happen:**

Should meet Lasan at Thunder Totem to finish the ritual

**Comment by Arkanheal** [comment] 2021-11-24 09:43
Duplicate of #2853. Closing.
For now you can complete the quest by not taking the bird and walking all the way to Thundertotem (you'll need to abandon the quest and taking it again)

**Closed as completed by Arkanheal** 2021-11-24 09:43 UTC
