### ISSUE TITLE
[Tyce] - Holy Priest: Serendipity and Holy Word: Serenity

### ISSUE THREAD

**Issue by IntroverseLaw** [GuabinaCore/WoWKoi#2729] opened 2021-08-10 18:36 UTC
**Links:**

https://www.wowhead.com/spell=2050/holy-word-serenity
https://www.wowhead.com/spell=63733/holy-words#changelog
https://www.wowhead.com/spell=2061/flash-heal

**What is happening:**
 
When I cast any spell that triggers Serendipity and use Holy Word: Serenity at the end of the cast, the later one doesn't go off right away, and some kind of ghost global cooldown is counted before I can use it. Obs: Holy Word: Serenity is the only holy word spell that has this issue, and any Serendipity trigger casted into Holy Word: Sanctify or Holy Word: Chastise works perfectly fine.
 
If the level 75 talent Piety is taken, making Prayer of Mending also proc Serendipity, casting it into Holy Word: Serenity now has the same issue (something that doesn't happen when you cast PoM into HW:Serenity without the talent). This leads me to believe it has to do with the Serendipity passive, but could also be involved in a global cooldown or spell queue problem.
 
Sadly, I'm not able to record myself to properly show the issue happening, but it's easily reproducible. Just in case it's not actually general, but specific to the amount of haste the player has, here's my current haste, flash heal cast time, and global cooldown:

Current Haste: 25,37% (9050)
Current Flash Heal cast time: 1.5s
Current global cooldown: 1.196s

**What should happen:**

A very common practice to optmize GCDs is to cast a spell and, at the end of it, use an instant spell. Since the cast time of the first one is longer than the GCD, the second spell goes off right away. That should be true for every two spells that fit those requirements, regardless of a passive working on the cooldown of the second spell.

**Comment by Arkanheal** [comment] 2021-11-26 21:33
Probably duplicate of #2535.
Closing this one for now.

**Closed as completed by Arkanheal** 2021-11-26 21:33 UTC
