### ISSUE TITLE
[Core] - Rogue Spell: Roll the bones - leach doesn't work

### ISSUE THREAD

**Issue by solini123** [GuabinaCore/WoWKoi#1443] opened 2020-05-22 18:08 UTC
**Links:**

from WoWHead or our Armory
https://www.wowhead.com/spell=193316/roll-the-bones

**What is happening:**
Whenever I get Leach/Attack Speed buff from RLD spell, only the attack speed part works. Leach doesn't

**What should happen:**
Leach should work.

**Comment by antonioyu0505** [comment] 2020-05-23 02:44
Duplicate of #893.

**Closed as completed** 2020-10-19 16:52 UTC
Labels: Core, Rogue
