### ISSUE TITLE
[Zone] Thunder Totem (Highmountain) Elevators

### ISSUE THREAD

**Issue by Sariet** [GuabinaCore/WoWKoi#3134] opened 2021-11-15 04:44 UTC
Sometimes the elevators vanish and you fall to your death.

The elevators shouldn't vanish and send you to the Valkyries

https://www.youtube.com/watch?v=swqoagCeYp4

**Comment by Arkanheal** [comment] 2021-11-24 16:04
Duplicate of #2483. Closing

**Closed as completed by Arkanheal** 2021-11-24 16:04 UTC
