### ISSUE TITLE
[Core] - Outlaw Rogue Riposte

### ISSUE THREAD

**Issue by bonfim97** [GuabinaCore/WoWKoi#1240] opened 2020-05-04 14:50 UTC
**Links:**

https://www.wowhead.com/spell=199754/riposte

**What is happening:**
It is parrying, but it's not doing damage.

**What should happen:**
Every 3 seconds one of the parrys deals damage.

**Comment by antonioyu0505** [comment] 2020-05-13 23:18
Duplicate of #648.

**Closed as completed** 2020-10-19 16:53 UTC
Labels: Core, Rogue
